### ISSUE TITLE
Error run docker file.

### ISSUE THREAD

**Issue by TarasRozputnii** [flytreeleft/nexus3-keycloak-plugin#13]
Before run i add keycloak.json in docker folder.
I run command:
```bash
sudo bash ./docker/build.sh
sudo bash ./docker/run.sh
```
I have error in nexus container
```
Error installing bundle listed in startup.properties with url: mvn:org.github.flytreeleft/nexus3-keycloak-plugin/0.3.2-SNAPSHOT and startlevel: 200
java.lang.NullPointerException
        at org.apache.karaf.main.Main.destroy(Main.java:634)
        at org.sonatype.nexus.karaf.NexusMain.main(NexusMain.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:63)
```

**Comment by flytreeleft** [comment]
Fixed in #14 . Thanks @TarasRozputnii again!
