### ISSUE TITLE
Missing org.sonatype.nexus.security.authz ?

### ISSUE THREAD

**Issue by bjolivot** [flytreeleft/nexus3-keycloak-plugin#15]
Hello!
I can't run the plugin.

Nexus v3.2.1
nexus3-keycloak-plugin-0.3.2-SNAPSHOT.jar built with maven

2019-02-13 11:34:56,605+0100 ERROR [FelixDispatchQueue] *SYSTEM nexus3-keycloak-plugin - FrameworkEvent ERROR - nexus3-keycloak-plugin
org.osgi.framework.BundleException: Unable to resolve nexus3-keycloak-plugin [46](R 46.0): missing requirement [nexus3-keycloak-plugin [46](R 46.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.security.authz)(version>=3.6.0)) Unresolved requirements: [[nexus3-keycloak-plugin [46](R 46.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.security.authz)(version>=3.6.0))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) [na:na]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) [na:na]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) [na:na]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [na:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-02-13 11:34:56,607+0100 ERROR [FelixStartLevel] *SYSTEM java.lang.Throwable - org.osgi.framework.BundleException: Unable to resolve nexus3-keycloak-plugin [46](R 46.0): missing requirement [nexus3-keycloak-plugin [46](R 46.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.security.authz)(version>=3.6.0)) Unresolved requirements: [[nexus3-keycloak-plugin [46](R 46.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.security.authz)(version>=3.6.0))]

Could you help me ?

**Comment by bjolivot** [comment]
Message is clear, i need nexus >= 3.6...sorry
