### ISSUE TITLE
Default Admin: HttpResponseException: Unexpected response from server: 403 / Forbidden

### ISSUE THREAD

**Issue by devent** [flytreeleft/nexus3-keycloak-plugin#21]
Hello. For some reason I now get the HttpResponseException: Unexpected response from server: 403 / Forbidden if I'm login with the **default** admin account of Nexus and try to see the users from the Keycloak realm. The default admin is in the `nx-admin` role.

Sonatype Nexus Repository Manager
OSS 3.15.2-01
nexus3-keycloak-plugin 0.3.4-pre0-SNAPSHOT

The `nx-admin` user should have access to everything?

Error log:

The user eiv5uT is the default admin user, not a Keycloak user.

![grafik](https://user-images.githubusercontent.com/82924/61719972-380a9d80-ad66-11e9-8838-508072fef1f5.png)

```
2019-07-23 14:09:40,894+0000 ERROR [qtp194600035-47] eiv5uT org.sonatype.nexus.extdirect.internal.ExtDirectExceptionHandler - Failed to invoke action method: coreui_User.read, java-method: org.sonatype.nexus.coreui.UserComponent.read
org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpResponseException: Unexpected response from server: 403 / Forbidden
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:65)
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.execute(HttpMethodResponse.java:34)
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakAdminClient.findUsers(KeycloakAdminClient.java:154)
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.NexusKeycloakClient.findUserByCriteria(NexusKeycloakClient.java:128)
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakUserManager.searchUsers(KeycloakUserManager.java:71)
        at org.sonatype.nexus.security.internal.DefaultSecuritySystem.searchUsers(DefaultSecuritySystem.java:415)
```

**Comment by flytreeleft** [comment]
@devent It seems that the Nexus3 realm client of Keycloak has no permission to view the Keycloak users.

Check [Configure Keycloak realm client](https://github.com/flytreeleft/nexus3-keycloak-plugin#4-configure-keycloak-realm-client) to assign `view-realm`, `view-clients` and `view-users` to the Nexus3 realm client in Keycloak.

**Comment by devent** [comment]
@flytreeleft Thank you for your reply. The client is correctly configured according to the docu. It was already working fine for months. I don't know what happened.

I just wanted to login to Nexus to see some private repository.

![grafik](https://user-images.githubusercontent.com/82924/61778160-84a1b780-adfe-11e9-804e-c7ef4fb722ef.png)

![grafik](https://user-images.githubusercontent.com/82924/61778233-a69b3a00-adfe-11e9-8c49-ae356108289a.png)

**Comment by devent** [comment]
To clarify, I was using the nexus3-keycloak-plugin version 0.2.1-SNAPSHOT. I got the error already with the 0.2.1 version and I tried to update the plugin to the current 0.3.4-pre0-SNAPSHOT. 

For some reason the Jenkins user (from Keycloak) can still login in Nexus.

**Comment by flytreeleft** [comment]
@devent You got 403 error because the realm client has no permission to do the user query. 
You can:
* try to update `$install_dir/etc/keycloak.json` (Please read [Create keycloak.json](https://github.com/flytreeleft/nexus3-keycloak-plugin#5-create-keycloakjson)), then check the `nx-admin` user whether can view all Keycloak users or not;
* if it's not working, try to disable `Authorization Enabled` in `Settings` page of the realm client, and check again;

If it's still not working, just paste the error logs of Keycloak and Nexus3 please.

**Comment by devent** [comment]
I tried what you wrote, but it still fails with the same error.
I also tried to create a new client and followed your setup guide, it's still the same error.

Nexus logs:
```
2019-08-19 12:22:31,233+0000 ERROR [qtp1848252304-53] eiv5uT org.sonatype.nexus.extdirect.internal.ExtDirectExceptionHandler - Failed to invoke action method: coreui_User.read, java-method: org.sonatype.nexus.coreui.UserComponent.read
org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpResponseException: Unexpected response from server: 403 / Forbidden
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:65)
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.execute(HttpMethodResponse.java:34)
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakAdminClient.findUsers(KeycloakAdminClient.java:154)
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.NexusKeycloakClient.findUserByCriteria(NexusKeycloakClient.java:128)
        at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakUserManager.searchUsers(KeycloakUserManager.java:71)
        at org.sonatype.nexus.security.internal.DefaultSecuritySystem.searchUsers(DefaultSecuritySystem.java:415)
        at org.sonatype.nexus.security.SecuritySystem$searchUsers.call(Unknown Source)
        at org.sonatype.nexus.coreui.UserComponent.read(UserComponent.groovy:91)
        at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:23)
        at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
        at org.apache.shiro.guice.aop.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:49)
        at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
        at org.apache.shiro.guice.aop.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeJavaMethod(DispatcherBase.java:142)
        at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeMethod(DispatcherBase.java:133)
        at org.sonatype.nexus.extdirect.internal.ExtDirectDispatcher.invokeMethod(ExtDirectDispatcher.java:82)
        at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.dispatch(DispatcherBase.java:63)
        at com.softwarementors.extjs.djn.router.processor.standard.StandardRequestProcessorBase.dispatchStandardMethod(StandardRequestProcessorBase.java:73)
        at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.processIndividualRequest(JsonRequestProcessor.java:502)
        at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.processIndividualRequestsInThisThread(JsonRequestProcessor.java:150)
        at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.process(JsonRequestProcessor.java:133)
        at com.softwarementors.extjs.djn.router.RequestRouter.processJsonRequest(RequestRouter.java:83)
        at com.softwarementors.extjs.djn.servlet.DirectJNgineServlet.processRequest(DirectJNgineServlet.java:632)
        at com.softwarementors.extjs.djn.servlet.DirectJNgineServlet.doPost(DirectJNgineServlet.java:595)
        at org.sonatype.nexus.extdirect.internal.ExtDirectServlet.doPost(ExtDirectServlet.java:129)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
        at com.google.inject.servlet.DynamicServletPipeline.service(DynamicServletPipeline.java:71)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:85)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:101)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.sonatype.nexus.licensing.internal.LicensingRedirectFilter.doFilter(LicensingRedirectFilter.java:108)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.sonatype.nexus.internal.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:68)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.sonatype.nexus.internal.web.EnvironmentFilter.doFilter(EnvironmentFilter.java:101)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.sonatype.nexus.internal.web.HeaderPatternFilter.doFilter(HeaderPatternFilter.java:98)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.DynamicFilterPipeline.dispatch(DynamicFilterPipeline.java:104)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.sonatype.nexus.bootstrap.osgi.DelegatingFilter.doFilter(DelegatingFilter.java:73)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:505)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
        at java.lang.Thread.run(Thread.java:748)
```

There are no Keycloak logs. Keycloak will only output error if I set a wrong client/credentials.

**Comment by flytreeleft** [comment]
@devent Please tell me, what is the Keycloak version that you use?

**Comment by devent** [comment]
Sure. Version 5.0.0

**Comment by devent** [comment]
Is there an issue that the Nexus default admin user is "eiv5uT" and not "admin"? I always change the default admin user to something other than "admin" for security reasons.

**Comment by flytreeleft** [comment]
@devent Not sure, but I will check that as soon as possible.

**Comment by flytreeleft** [comment]
@devent That was so strange, I can't find the reason :(.

If I remove the client role `view-users` from the Nexus3 realm client in Keycloak, then try to access the Keycloak users in Nexus3, it will cause the same error.

It will not work event if I add `view-users` role back to the Nexus3 realm client, the only way is restarting the Nexus3 server.

Please create a new realm in Keycloak for testing, and try it again. Then export the realm with clients and roles from Keycloak, and paste the json file, I will try to check it in my local developing environment. Thanks!

**Comment by flytreeleft** [comment]
Close the inactive issue, if there still are some problems, please just make a comment or create a new issue :)

**Comment by josedev-union** [comment]
> 
> 
> @devent You got 403 error because the realm client has no permission to do the user query.
> You can:
> 
>     * try to update `$install_dir/etc/keycloak.json` (Please read [Create keycloak.json](https://github.com/flytreeleft/nexus3-keycloak-plugin#5-create-keycloakjson)), then check the `nx-admin` user whether can view all Keycloak users or not;
> 
>     * if it's not working, try to disable `Authorization Enabled` in `Settings` page of the realm client, and check again;
> 
> 
> If it's still not working, just paste the error logs of Keycloak and Nexus3 please.

Hi @flytreeleft, why do we need to disable `Authorization Enabled` in `Settings` page of the realm client?
Before that, I got 401 error.

**Comment by flytreeleft** [comment]
@josedev-union Because if you enable the authorization, you should configure the resource `Authorization` precisely in the client setting page. That is too complicated to determine what is true, it is so to me at least ;-). And it is not necessary for this plugin, so just disable it.

**Comment by josedev-union** [comment]
@flytreeleft ok, thanks.
