### ISSUE TITLE
403 Forbidden with Keycloak 6.0.1

### ISSUE THREAD

**Issue by smarnley** [flytreeleft/nexus3-keycloak-plugin#33]
Hi,
I have set up a new Nexus OSS 3 server, installed your plugin and configured both sides as detailed but I am getting a persistent 403 error when logging in as a user authorised through Keycloak. It seems that the user gets authorised by Keycloak but doesn't pick up any permissions.

Nexus OSS 3.19.1-01
Keycloak 6.0.1

Error:
```
2019-12-02 12:37:06,280+0000 WARN  [qtp1327413510-43]  shane.marnley org.sonatype.nexus.rapture.internal.state.StateComponent - Failed to get state from com.google.inject.internal.InjectorImpl$2 (ignored)
org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpResponseException: Unexpected response from server: 403 / Forbidden
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:65)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.execute(HttpMethodResponse.java:34)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakAdminClient.getUser(KeycloakAdminClient.java:121)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.NexusKeycloakClient.findUserByUserId(NexusKeycloakClient.java:100)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakUserManager.getUser(KeycloakUserManager.java:77)
	at org.sonatype.nexus.security.internal.DefaultSecuritySystem.findUser(DefaultSecuritySystem.java:335)
	at org.sonatype.nexus.security.internal.DefaultSecuritySystem.getUser(DefaultSecuritySystem.java:364)
	at org.sonatype.nexus.security.internal.DefaultSecuritySystem.currentUser(DefaultSecuritySystem.java:355)
	at org.sonatype.nexus.internal.selector.SelectorManagerImpl.browseActive(SelectorManagerImpl.java:210)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$GuardImpl.run(StateGuard.java:272)
	at org.sonatype.nexus.common.stateguard.GuardedInterceptor.invoke(GuardedInterceptor.java:53)
	at org.sonatype.nexus.repository.security.RepositoryPermissionChecker.subjectHasAnyContentSelectorAccessTo(RepositoryPermissionChecker.java:181)
	at org.sonatype.nexus.repository.security.RepositoryPermissionChecker.userCanBrowseRepositories(RepositoryPermissionChecker.java:98)
	at org.sonatype.nexus.repository.security.RepositoryPermissionChecker.userCanBrowseRepositories(RepositoryPermissionChecker.java:136)
	at org.sonatype.nexus.repository.security.RepositoryPermissionChecker$userCanBrowseRepositories.call(Unknown Source)
	at org.sonatype.nexus.coreui.RepositoryComponent.getBrowseableFormats(RepositoryComponent.groovy:137)
	at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:23)
	at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
	at org.sonatype.nexus.coreui.RepositoryComponent.getState(RepositoryComponent.groovy:149)
	at org.sonatype.nexus.rapture.internal.state.StateComponent.getState(StateComponent.java:87)
	at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:23)
	at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeJavaMethod(DispatcherBase.java:142)
	at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeMethod(DispatcherBase.java:133)
	at org.sonatype.nexus.extdirect.internal.ExtDirectDispatcher.invokeMethod(ExtDirectDispatcher.java:82)
	at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.dispatch(DispatcherBase.java:63)
	at com.softwarementors.extjs.djn.router.processor.poll.PollRequestProcessor.process(PollRequestProcessor.java:145)
	at org.sonatype.nexus.extdirect.internal.ExtDirectServlet$3.processPollRequest(ExtDirectServlet.java:253)
	at com.softwarementors.extjs.djn.servlet.DirectJNgineServlet.processRequest(DirectJNgineServlet.java:636)
	at com.softwarementors.extjs.djn.servlet.DirectJNgineServlet.doPost(DirectJNgineServlet.java:595)
	at org.sonatype.nexus.extdirect.internal.ExtDirectServlet.doPost(ExtDirectServlet.java:135)
	at com.softwarementors.extjs.djn.servlet.DirectJNgineServlet.doGet(DirectJNgineServlet.java:568)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.DynamicServletPipeline.service(DynamicServletPipeline.java:71)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:85)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:101)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.sonatype.nexus.licensing.internal.LicensingRedirectFilter.doFilter(LicensingRedirectFilter.java:114)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:79)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.EnvironmentFilter.doFilter(EnvironmentFilter.java:101)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.HeaderPatternFilter.doFilter(HeaderPatternFilter.java:98)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.DynamicFilterPipeline.dispatch(DynamicFilterPipeline.java:104)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.sonatype.nexus.bootstrap.osgi.DelegatingFilter.doFilter(DelegatingFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```

We've been digging around for a while now and can't find the source of the problem.

Regards,
Shane.

**Comment by flytreeleft** [comment]
@smarnley Please do some checkings as [Configure Keycloak realm client](https://github.com/flytreeleft/nexus3-keycloak-plugin#4-configure-keycloak-realm-client) . If it still exists, please paste the Keycloak's log when the user login failed.

**Comment by smarnley** [comment]
We don't have any Keycloak logs at the moment but it seems to be related to using a different realm to "master". We have tested using curl to get the token and then access the URL that returns a 403 and it works on the master realm but not on the other realm.

**Comment by smarnley** [comment]
We have now tested with a client on master and it works ok but exactly the same config on our other realm fails.
Keycloak logs below...

Master realm (working):
```
x.x.x.x - - [03/Dec/2019:15:57:16 +0000] "POST /auth/realms/master/protocol/openid-connect/token HTTP/1.1" 200 3146
x.x.x.x - - [03/Dec/2019:15:57:18 +0000] "GET /auth/admin/realms/master/users?search=&grant_type=access_token HTTP/1.1" 200 3092
x.x.x.x - - [03/Dec/2019:15:57:19 +0000] "GET /auth/admin/realms/master/users?grant_type=access_token&username=admin HTTP/1.1" 200 331
```

Corp realm (fails):
```
x.x.x.x - - [03/Dec/2019:15:56:39 +0000] "POST /auth/realms/corp/protocol/openid-connect/token HTTP/1.1" 200 2060
x.x.x.x - - [03/Dec/2019:15:56:39 +0000] "GET /auth/admin/realms/corp/users?search=&grant_type=access_token HTTP/1.1" 403 -
```

Debug:
```
2019-12-03 15:56:39,058 DEBUG [io.undertow.request] (default I/O-3) Matched prefix path /auth for path /auth/realms/corp/protocol/openid-connect/token
2019-12-03 15:56:39,059 DEBUG [io.undertow.request.security] (default task-18) Attempting to authenticate /auth/realms/corp/protocol/openid-connect/token, authentication required: false
2019-12-03 15:56:39,059 DEBUG [io.undertow.request.security] (default task-18) Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@7ca9b779 for /auth/realms/corp/protocol/openid-connect/token
2019-12-03 15:56:39,059 DEBUG [io.undertow.request.security] (default task-18) Authentication result was ATTEMPTED for /auth/realms/corp/protocol/openid-connect/token
2019-12-03 15:56:39,059 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-18) new JtaTransactionWrapper
2019-12-03 15:56:39,059 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-18) was existing? false
2019-12-03 15:56:39,059 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) RESTEASY002315: PathInfo: /realms/corp/protocol/openid-connect/token
2019-12-03 15:56:39,059 DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (default task-18) Hibernate RegisteredSynchronization successfully registered with JTA platform
2019-12-03 15:56:39,059 DEBUG [org.keycloak.authentication.AuthenticationProcessor] (default task-18) AUTHENTICATE CLIENT
2019-12-03 15:56:39,059 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (default task-18) client authenticator: client-secret
2019-12-03 15:56:39,059 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (default task-18) client authenticator SUCCESS: client-secret
2019-12-03 15:56:39,059 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (default task-18) Client bs-nexus authenticated by client-secret
2019-12-03 15:56:39,059 DEBUG [org.hibernate.SQL] (default task-18)
2019-12-03 15:56:39,059 DEBUG [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] (default task-18) MysqlDS: getConnection(null, WrappedConnectionRequestInfo@1bf648b1[userName=keycloak]) [0/15]
2019-12-03 15:56:39,060 DEBUG [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (default task-18) HHH000387: ResultSet's statement was not registered
2019-12-03 15:56:39,060 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (default task-18) Initiating JDBC connection release from afterStatement
2019-12-03 15:56:39,060 DEBUG [org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader] (default task-18) Done entity load : org.keycloak.models.jpa.entities.ClientScopeEntity#11d47e3e-ef66-4b7f-b5fa-65d703578d27
2019-12-03 15:56:39,062 DEBUG [org.keycloak.events] (default task-18) type=REFRESH_TOKEN, realmId=corp, clientId=bs-nexus, userId=3a544fb8-749f-48d6-9291-e16cc5fdafd8, ipAddress=X.X.X.X, token_id=9d4fb9fe-a67a-4d56-ae74-d57df66e17b4, grant_type=refresh_token, refresh_token_type=Refresh, updated_refresh_token_id=55e10ba6-bef9-4c13-91b6-9c5d1aa94bdb, scope='email profile', refresh_token_id=85ba88b2-f834-4371-8827-0c080b305404, client_auth_method=client-secret
2019-12-03 15:56:39,062 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-18) JtaTransactionWrapper  commit
2019-12-03 15:56:39,062 DEBUG [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] (default task-18) MysqlDS: returnConnection(64ad45a, false) [0/15]
2019-12-03 15:56:39,062 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (default task-18) Initiating JDBC connection release from afterTransaction
2019-12-03 15:56:39,062 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-18) JtaTransactionWrapper end
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) MessageBodyWriter: org.jboss.resteasy.spi.ResteasyProviderFactory$SortedKey
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) MessageBodyWriter: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) MessageBodyWriter: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) Interceptor Context: org.jboss.resteasy.core.interception.ServerWriterInterceptorContext,  Method : proceed
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) WriterInterceptor: org.jboss.resteasy.security.doseta.DigitalSigningInterceptor
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.security.doseta.i18n] (default task-18) Interceptor : org.jboss.resteasy.security.doseta.DigitalSigningInterceptor,  Method : aroundWriteTo
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) Interceptor Context: org.jboss.resteasy.core.interception.ServerWriterInterceptorContext,  Method : proceed
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) MessageBodyWriter: org.jboss.resteasy.spi.ResteasyProviderFactory$SortedKey
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) MessageBodyWriter: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
2019-12-03 15:56:39,062 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) Provider : org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider,  Method : writeTo
2019-12-03 15:56:39,065 DEBUG [io.undertow.request] (default I/O-3) Matched prefix path /auth for path /auth/admin/realms/corp/users
2019-12-03 15:56:39,065 DEBUG [io.undertow.request.security] (default task-16) Attempting to authenticate /auth/admin/realms/corp/users, authentication required: false
2019-12-03 15:56:39,065 DEBUG [io.undertow.request.security] (default task-16) Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@7ca9b779 for /auth/admin/realms/corp/users
2019-12-03 15:56:39,065 DEBUG [io.undertow.request.security] (default task-16) Authentication result was ATTEMPTED for /auth/admin/realms/corp/users
2019-12-03 15:56:39,065 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-16) new JtaTransactionWrapper
2019-12-03 15:56:39,065 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-16) was existing? false
2019-12-03 15:56:39,066 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-16) RESTEASY002315: PathInfo: /admin/realms/corp/users
2019-12-03 15:56:39,066 DEBUG [org.keycloak.services.resources.admin.AdminRoot] (default task-16) authenticated admin access for: service-account-bs-nexus
2019-12-03 15:56:39,066 DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (default task-16) Hibernate RegisteredSynchronization successfully registered with JTA platform
2019-12-03 15:56:39,067 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-16) JtaTransactionWrapper rollback
2019-12-03 15:56:39,067 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (default task-16) Initiating JDBC connection release from afterTransaction
2019-12-03 15:56:39,067 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-16) JtaTransactionWrapper end
```

**Comment by smarnley** [comment]
Summary: It works in Master realm.  In sub realm the user can authenticate in Nexus (and shows as logged in) but no roles are assigned and 403 errors are displayed.  Logging into Nexus as local admin user, then going to "Users" and selecting "Keycloak" in the source dropdown also displays 403 error.

**Comment by flytreeleft** [comment]
@smarnley The `403` error means that the client in Keycloak has no permission to access the API.

So you should make sure the client in Keycloak has permissions at least including `view-realm`, `view-clients` and `view-users`:

![](https://raw.githubusercontent.com/flytreeleft/nexus3-keycloak-plugin/master/docs/images/choose-service-account-roles.png)

And you need to update `$install_dir/etc/keycloak.json` in Nexus when you want to change to another realm, just following the menu path in Keyclok: `[Choose your realm] -> Clients -> [nexus3 client] -> Installation -> [Choose 'Keycloak OIDC JSON' option]`.

Of course, you should create some role mappings in Nexus3 for the Keycloak users.

**Comment by smarnley** [comment]
@flytreeleft we have now resolved the problem.
We needed to add a scope mapping to the "roles" client scope.
![Screenshot 2020-01-21 at 10 34 39](https://user-images.githubusercontent.com/20399791/72798042-18333400-3c3a-11ea-9db1-2a66576a8d59.png)
Obviously this is just configured for admin users at the moment but we would need to do the same for "nexus-users" and such.
