### ISSUE TITLE
Permission on server

### ISSUE THREAD

**Issue by thpr89** [flytreeleft/nexus3-keycloak-plugin#46]
First of all thank you for the plugin. It makes it even easier to use the same authentication provider for applications and nexus too. 

I have a question about the permission. When i use your DockerFile to create an image and run a container, everything works fine on my own machine. Pushing the configuration to a server and running the container there does not work. On startup i got a permission denied on the hosts folder i mounted as the volume for nexus-data. <br>
Other images (e.g. postgres) work fine on that machine with a mounted folder. So i do not think thats it has something in common with my privilegues on the server.<br>

docker-compose file: <br>

```
nexus
    container_name: test_nexus
    image: test:latest
    volumes: 
     - ./nexus/nexus-data:/nexus-data
     - ./nexus/keycloak.json:/opt/sonatype/nexus/etc/keycloak.json:ro
    ports:
     - 8081:8081
    networks:
     - test-net
```
Log
```
mkdir: cannot create directory '../sonatype-work/nexus3/log': Permission denied
mkdir: cannot create directory '../sonatype-work/nexus3/tmp': Permission denied
Warning:  Cannot open log file: ../sonatype-work/nexus3/log/jvm.log
Warning:  Forcing option -XX:LogFile=/tmp/jvm.log
OpenJDK 64-Bit Server VM warning: Cannot open file ../sonatype-work/nexus3/log/jvm.log due to No such file or directory

java.io.FileNotFoundException: ../sonatype-work/nexus3/tmp/i4j_ZTDnGON8hezynsMX2ZCYAVDtQog=.lock (No such file or directory)
 	at java.io.RandomAccessFile.open0(Native Method)
 	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at com.install4j.runtime.launcher.util.SingleInstance.check(SingleInstance.java:72)
 	at com.install4j.runtime.launcher.util.SingleInstance.checkForCurrentLauncher(SingleInstance.java:31)
 	at com.install4j.runtime.launcher.UnixLauncher.checkSingleInstance(UnixLauncher.java:88)
 	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:67)
java.io.FileNotFoundException: /nexus-data/karaf.pid (Permission denied)
 	at java.io.FileOutputStream.open0(Native Method)
 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
 	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
 	at org.apache.karaf.main.InstanceHelper.writePid(InstanceHelper.java:126)
 	at org.apache.karaf.main.Main.launch(Main.java:243)
 	at org.sonatype.nexus.karaf.NexusMain.launch(NexusMain.java:113)
 	at org.sonatype.nexus.karaf.NexusMain.main(NexusMain.java:52)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
 	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:69)
java.lang.RuntimeException: /nexus-data/log/karaf.log (No such file or directory)
 	at org.apache.karaf.main.util.BootstrapLogManager.getDefaultHandlerInternal(BootstrapLogManager.java:102)
 	at org.apache.karaf.main.util.BootstrapLogManager.getDefaultHandlersInternal(BootstrapLogManager.java:137)
 	at org.apache.karaf.main.util.BootstrapLogManager.getDefaultHandlers(BootstrapLogManager.java:70)
 	at org.apache.karaf.main.util.BootstrapLogManager.configureLogger(BootstrapLogManager.java:75)
 	at org.apache.karaf.main.Main.launch(Main.java:244)
 	at org.sonatype.nexus.karaf.NexusMain.launch(NexusMain.java:113)
 	at org.sonatype.nexus.karaf.NexusMain.main(NexusMain.java:52)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
 	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:69)
Caused by: java.io.FileNotFoundException: /nexus-data/log/karaf.log (No such file or directory)
 	at java.io.FileOutputStream.open0(Native Method)
 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
 	at org.apache.karaf.main.util.BootstrapLogManager$SimpleFileHandler.open(BootstrapLogManager.java:193)
 	at org.apache.karaf.main.util.BootstrapLogManager$SimpleFileHandler.<init>(BootstrapLogManager.java:182)
 	at org.apache.karaf.main.util.BootstrapLogManager.getDefaultHandlerInternal(BootstrapLogManager.java:100)
 	... 12 more
 Error creating bundle cache.
 Unable to update instance pid: Unable to create directory /nexus-data/instances
```
Any suggestion how to fix it?
Regards

**Comment by thpr89** [comment]
fixed it on my own. 
thanks again for the plugin
