### ISSUE TITLE
Is there any docker image including this plugin?

### ISSUE THREAD

**Issue by zhrum** [flytreeleft/nexus3-keycloak-plugin#6]
Is there any docker image including this plugin?

**Comment by flytreeleft** [comment]
@zhrum I think maybe no such docker image exists. But, you can build it by yourself.

- Create a `Dockerfile`:

```dockerfile
# https://github.com/cavemandaveman/nexus
FROM cavemandaveman/nexus:3.6.0-02

ENV NEXUS_PLUGINS ${NEXUS_HOME}/system

# https://github.com/flytreeleft/nexus3-keycloak-plugin
ENV KEYCLOAK_PLUGIN_VERSION 0.2.0-SNAPSHOT
ENV KEYCLOAK_PLUGIN org.github.flytreeleft/nexus3-keycloak-plugin/${KEYCLOAK_PLUGIN_VERSION}

ADD https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/download/${KEYCLOAK_PLUGIN_VERSION}/nexus3-keycloak-plugin-${KEYCLOAK_PLUGIN_VERSION}.jar \
    ${NEXUS_PLUGINS}/org/github/flytreeleft/nexus3-keycloak-plugin/${KEYCLOAK_PLUGIN_VERSION}/nexus3-keycloak-plugin-${KEYCLOAK_PLUGIN_VERSION}.jar
RUN echo "mvn\\:${KEYCLOAK_PLUGIN} = 200" >> ${NEXUS_HOME}/etc/karaf/startup.properties
```

- Build the image (Please replace `<your-nexus3>` with what you like):

```bash
#!/bin/bash

IMAGE_NAME="<your-nexus3>"
IMAGE_VERSION=3.6.0-02-r1

docker build  -t ${IMAGE_NAME}:${IMAGE_VERSION} .
```

- Prepare your `keycloak.json`([more detail](https://github.com/flytreeleft/nexus3-keycloak-plugin#5-create-keycloakjson)):

```json
{
  "realm": "default",
  "auth-server-url": "http://localhost:8080/auth",
  "ssl-required": "external",
  "resource": "nexus3",
  "credentials": {
    "secret": "a203feab-4bcf-4e73-b66e-05adc1da0da6"
  },
  "policy-enforcer": {}
}
```

- Start your container:

```bash
#!/bin/bash

NEXUS_HOME=/opt/sonatype/nexus

DCR_NAME=nexus3
DCR_IMAGE="<your-nexus3>"
DCR_IMAGE_VERSION=3.6.0-02-r1

docker run -d --name ${DCR_NAME} \
                --restart always \
                --ulimit nofile=655360 \
                -e NEXUS_CONTEXT="/" \
                -e JAVA_MAX_MEM=4096M \
                -v /path/to/keycloak.json:${NEXUS_HOME}/etc/keycloak.json:ro \
                -p 8081:8081 \
                -p 5000:5000 \
                ${DCR_IMAGE}:${DCR_IMAGE_VERSION}
```

**Comment by zhrum** [comment]
I have this when adding roles in nexus.
Error executing http method [org.apache.http.client.methods.RequestBuilder@6f5fbd63].

**Comment by flytreeleft** [comment]
@zhrum Is there more details?

**Comment by boardend** [comment]
@flytreeleft thanks for your Docker recipe. I got your plugin running earlier this week, by inspecting Dockerfiles from other Nexus 3 Plugins. It would be nice to add a "official" Dockerfile to this repo?

@zhrum After setting up my Nexus 3 Docker container with a Keycloak 4 Realm, I've also got an Exception in RequestBuilder:

```log
2018-10-05 06:56:15,572+0000 INFO  [qtp287050655-131] %USERNAME% org.sonatype.nexus.rapture.internal.security.SessionServlet - Created session for user: %USERNAME%
2018-10-05 06:56:16,027+0000 ERROR [pool-22-thread-6] %USERNAME% org.sonatype.nexus.extdirect.internal.ExtDirectServlet - Failed to invoke action method: outreach_Outreach.readStatus, java-method: com.sonatype.nexus.plugins.outreach.internal.ui.OutreachComponent.readStatus
java.lang.RuntimeException: Error executing http method [org.apache.http.client.methods.RequestBuilder@6257846e].
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:79)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.execute(HttpMethodResponse.java:34)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakAdminClient.getRealmClient(KeycloakAdminClient.java:84)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakAdminClient.getRealmClientRolesOfUser(KeycloakAdminClient.java:163)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.NexusKeycloakClient.findRolesByUser(NexusKeycloakClient.java:42)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakUserManager.completeUserRolesAndSource(KeycloakUserManager.java:59)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakUserManager.getUser(KeycloakUserManager.java:87)
     at org.sonatype.nexus.security.internal.DefaultSecuritySystem.findUser(DefaultSecuritySystem.java:334)
     at org.sonatype.nexus.security.internal.DefaultSecuritySystem.getUser(DefaultSecuritySystem.java:363)
     at com.sonatype.nexus.plugins.outreach.internal.OutreachHelper.hasAdminRole(OutreachHelper.java:65)
     at com.sonatype.nexus.plugins.outreach.Outreach$User.fromSubject(Outreach.java:70)
     at com.sonatype.nexus.plugins.outreach.Outreach$User$fromSubject.call(Unknown Source)
     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
     at com.sonatype.nexus.plugins.outreach.Outreach$User$fromSubject.call(Unknown Source)
     at com.sonatype.nexus.plugins.outreach.internal.ui.OutreachComponent.readStatus(OutreachComponent.groovy:56)
     at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:49)
     at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:47)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeJavaMethod(DispatcherBase.java:142)
     at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeMethod(DispatcherBase.java:133)
     at org.sonatype.nexus.extdirect.internal.ExtDirectServlet$3.invokeMethod(ExtDirectServlet.java:236)
     at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.dispatch(DispatcherBase.java:63)
     at com.softwarementors.extjs.djn.router.processor.standard.StandardRequestProcessorBase.dispatchStandardMethod(StandardRequestProcessorBase.java:73)
     at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.processIndividualRequest(JsonRequestProcessor.java:502)
     at com.softwarementors.extjs.djn.router.processor.standard.json.DefaultJsonRequestProcessorThread.processRequest(DefaultJsonRequestProcessorThread.java:72)
     at com.softwarementors.extjs.djn.servlet.ssm.SsmJsonRequestProcessorThread.processRequest(SsmJsonRequestProcessorThread.java:43)
     at org.sonatype.nexus.extdirect.internal.ExtDirectJsonRequestProcessorThread.access$1(ExtDirectJsonRequestProcessorThread.java:1)
     at org.sonatype.nexus.extdirect.internal.ExtDirectJsonRequestProcessorThread$1.call(ExtDirectJsonRequestProcessorThread.java:61)
     at org.sonatype.nexus.extdirect.internal.ExtDirectJsonRequestProcessorThread$1.call(ExtDirectJsonRequestProcessorThread.java:1)
     at com.google.inject.servlet.ServletScopes$4.call(ServletScopes.java:450)
     at org.sonatype.nexus.extdirect.internal.ExtDirectJsonRequestProcessorThread.processRequest(ExtDirectJsonRequestProcessorThread.java:75)
     at com.softwarementors.extjs.djn.router.processor.standard.json.DefaultJsonRequestProcessorThread.call(DefaultJsonRequestProcessorThread.java:56)
     at com.softwarementors.extjs.djn.router.processor.standard.json.DefaultJsonRequestProcessorThread.call(DefaultJsonRequestProcessorThread.java:30)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error parsing JSON response.
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.lambda$0(HttpMethodResponse.java:38)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:74)
     ... 39 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "authenticationFlowBindingOverrides" (class org.keycloak.representations.idm.ClientRepresentation), not marked as ignorable (38 known properties: "enabled", "clientAuthenticatorType", "redirectUris", "clientId", "authorizationServicesEnabled", "name", "implicitFlowEnabled", "registeredNodes", "nodeReRegistrationTimeout", "publicClient", "attributes", "protocol", "webOrigins", "protocolMappers", "id", "baseUrl", "surrogateAuthRequired", "adminUrl", "fullScopeAllowed", "frontchannelLogout", "clientTemplate", "directGrantsOnly", "rootUrl", "secret", "useTemplateMappers", "notBefore", "useTemplateScope", "standardFlowEnabled", "description", "directAccessGrantsEnabled", "useTemplateConfig", "serviceAccountsEnabled", "consentRequired", "access", "bearerOnly", "registrationAccessToken", "defaultRoles", "authorizationSettings"])
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 1, column: 1009] (through reference chain: java.util.ArrayList[0]->org.keycloak.representations.idm.ClientRepresentation["authenticationFlowBindingOverrides"])
     at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
     at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
     at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567)
     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1545)
     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3065)
     at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:85)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.lambda$0(HttpMethodResponse.java:36)
     ... 40 common frames omitted
2018-10-05 06:56:16,220+0000 ERROR [pool-22-thread-9] %USERNAME% org.sonatype.nexus.extdirect.internal.ExtDirectServlet - Failed to invoke action method: outreach_Outreach.readStatus, java-method: com.sonatype.nexus.plugins.outreach.internal.ui.OutreachComponent.readStatus
java.lang.RuntimeException: Error executing http method [org.apache.http.client.methods.RequestBuilder@17a1dda4].
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:79)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.execute(HttpMethodResponse.java:34)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakAdminClient.getRealmClient(KeycloakAdminClient.java:84)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakAdminClient.getRealmClientRolesOfUser(KeycloakAdminClient.java:163)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.NexusKeycloakClient.findRolesByUser(NexusKeycloakClient.java:42)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakUserManager.completeUserRolesAndSource(KeycloakUserManager.java:59)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakUserManager.getUser(KeycloakUserManager.java:87)
     at org.sonatype.nexus.security.internal.DefaultSecuritySystem.findUser(DefaultSecuritySystem.java:334)
     at org.sonatype.nexus.security.internal.DefaultSecuritySystem.getUser(DefaultSecuritySystem.java:363)
     at com.sonatype.nexus.plugins.outreach.internal.OutreachHelper.hasAdminRole(OutreachHelper.java:65)
     at com.sonatype.nexus.plugins.outreach.Outreach$User.fromSubject(Outreach.java:70)
     at com.sonatype.nexus.plugins.outreach.Outreach$User$fromSubject.call(Unknown Source)
     at com.sonatype.nexus.plugins.outreach.internal.ui.OutreachComponent.readStatus(OutreachComponent.groovy:56)
     at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:49)
     at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:47)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeJavaMethod(DispatcherBase.java:142)
     at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeMethod(DispatcherBase.java:133)
     at org.sonatype.nexus.extdirect.internal.ExtDirectServlet$3.invokeMethod(ExtDirectServlet.java:236)
     at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.dispatch(DispatcherBase.java:63)
     at com.softwarementors.extjs.djn.router.processor.standard.StandardRequestProcessorBase.dispatchStandardMethod(StandardRequestProcessorBase.java:73)
     at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.processIndividualRequest(JsonRequestProcessor.java:502)
     at com.softwarementors.extjs.djn.router.processor.standard.json.DefaultJsonRequestProcessorThread.processRequest(DefaultJsonRequestProcessorThread.java:72)
     at com.softwarementors.extjs.djn.servlet.ssm.SsmJsonRequestProcessorThread.processRequest(SsmJsonRequestProcessorThread.java:43)
     at org.sonatype.nexus.extdirect.internal.ExtDirectJsonRequestProcessorThread.access$1(ExtDirectJsonRequestProcessorThread.java:1)
     at org.sonatype.nexus.extdirect.internal.ExtDirectJsonRequestProcessorThread$1.call(ExtDirectJsonRequestProcessorThread.java:61)
     at org.sonatype.nexus.extdirect.internal.ExtDirectJsonRequestProcessorThread$1.call(ExtDirectJsonRequestProcessorThread.java:1)
     at com.google.inject.servlet.ServletScopes$4.call(ServletScopes.java:450)
     at org.sonatype.nexus.extdirect.internal.ExtDirectJsonRequestProcessorThread.processRequest(ExtDirectJsonRequestProcessorThread.java:75)
     at com.softwarementors.extjs.djn.router.processor.standard.json.DefaultJsonRequestProcessorThread.call(DefaultJsonRequestProcessorThread.java:56)
     at com.softwarementors.extjs.djn.router.processor.standard.json.DefaultJsonRequestProcessorThread.call(DefaultJsonRequestProcessorThread.java:30)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error parsing JSON response.
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.lambda$0(HttpMethodResponse.java:38)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:74)
     ... 37 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "authenticationFlowBindingOverrides" (class org.keycloak.representations.idm.ClientRepresentation), not marked as ignorable (38 known properties: "enabled", "clientAuthenticatorType", "redirectUris", "clientId", "authorizationServicesEnabled", "name", "implicitFlowEnabled", "registeredNodes", "nodeReRegistrationTimeout", "publicClient", "attributes", "protocol", "webOrigins", "protocolMappers", "id", "baseUrl", "surrogateAuthRequired", "adminUrl", "fullScopeAllowed", "frontchannelLogout", "clientTemplate", "directGrantsOnly", "rootUrl", "secret", "useTemplateMappers", "notBefore", "useTemplateScope", "standardFlowEnabled", "description", "directAccessGrantsEnabled", "useTemplateConfig", "serviceAccountsEnabled", "consentRequired", "access", "bearerOnly", "registrationAccessToken", "defaultRoles", "authorizationSettings"])
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 1, column: 1009] (through reference chain: java.util.ArrayList[0]->org.keycloak.representations.idm.ClientRepresentation["authenticationFlowBindingOverrides"])
     at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
     at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
     at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567)
     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1545)
     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3065)
     at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:85)
     at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.lambda$0(HttpMethodResponse.java:36)
     ... 38 common frames omitted
```

IMHO, this plugin is just not compatible with Keykloak 4 (see README.md, "It works with Nexus 3.x and Keycloak 3.x")

@flytreeleft Are there any plans supporting Keycloak >= 4? (Maybe it would just work, be letting Jackson ignore unknown Fields by default?)

**Comment by flytreeleft** [comment]
@boardend Maybe, this plugin should upgrade the dependencies of Keycloak to 4.x. But I am not sure whether it's compatible with Keycloak 3.x or not.

If I am lucky, I will do some work for upgrading it and other improvements in the day after tomorrow.

**Comment by flytreeleft** [comment]
@boardend  @zhrum Good news, I just upgraded the Keycloak to 4.x and it's compatible with Keycloak 3.x. All of you can try the new version [0.3.0-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.3.0-SNAPSHOT).

**Comment by flytreeleft** [comment]
For Docker image building, just read [#docker](https://github.com/flytreeleft/nexus3-keycloak-plugin#docker).

**Comment by boardend** [comment]
I can confirm, that with the latest Release (0.3.1-SNAPSHOT) the plugin is working against Keycloak 4. Also thanks for adding a Docker section to the Readme and providing the needed Scripts/Dockerfile.
