### ISSUE TITLE
ClassNotFoundException: org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm

### ISSUE THREAD

**Issue by d3473r** [flytreeleft/nexus3-keycloak-plugin#68]
Hi, when using the https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/download/v0.4.1/nexus3-keycloak-plugin-0.4.1-bundle.kar I'm getting a ClassNotFoundException

```
java.lang.ClassNotFoundException: org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm
	at java.lang.ClassLoader.findClass(ClassLoader.java:523)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at com.google.inject.internal.BytecodeGen$BridgeClassLoader.classicLoadClass(BytecodeGen.java:424)
	at com.google.inject.internal.BytecodeGen$BridgeClassLoader.loadClass(BytecodeGen.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.sonatype.nexus.security.internal.RealmManagerImpl.resolveRealms(RealmManagerImpl.java:241)
	at org.sonatype.nexus.security.internal.RealmManagerImpl.installRealms(RealmManagerImpl.java:219)
	at org.sonatype.nexus.security.internal.RealmManagerImpl.doStart(RealmManagerImpl.java:109)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:69)
	at org.sonatype.nexus.security.internal.RealmManagerImpl$$EnhancerByGuice$$ba76ef36.CGLIB$start$16(<generated>)
	at org.sonatype.nexus.security.internal.RealmManagerImpl$$EnhancerByGuice$$ba76ef36$$FastClassByGuice$$32745399.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:57)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.sonatype.nexus.security.internal.RealmManagerImpl$$EnhancerByGuice$$ba76ef36.start(<generated>)
	at org.sonatype.nexus.security.internal.DefaultSecuritySystem.doStart(DefaultSecuritySystem.java:124)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:69)
	at org.sonatype.nexus.security.internal.DefaultSecuritySystem$$EnhancerByGuice$$43dc7d2c.CGLIB$start$29(<generated>)
	at org.sonatype.nexus.security.internal.DefaultSecuritySystem$$EnhancerByGuice$$43dc7d2c$$FastClassByGuice$$c05a619b.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:57)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.sonatype.nexus.security.internal.DefaultSecuritySystem$$EnhancerByGuice$$43dc7d2c.start(<generated>)
	at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:199)
	at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:111)
	at org.sonatype.nexus.extender.NexusContextListener.moveToPhase(NexusContextListener.java:321)
	at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:218)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1431)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by flytreeleft** [comment]
@d3473r Did you put the KAR file into the directory `$install_dir/deploy/` ? And please note the `$install_dir/etc/karaf/startup.properties` should not be modified.

**Comment by d3473r** [comment]
Hmm, I cannot reproduce the error on a fresh container with 
```
version: '3'

services: 
  nexus:
    image: sonatype/nexus3:3.29.2
    container_name: nexus
    volumes:
      - ./deploy:/opt/sonatype/nexus/deploy
```
I guess my nexus container has some corrupted data.
