### ISSUE TITLE
Not logged into nexus after successfull login at keycloak SSO (edit: dns issue - SOLVED)

### ISSUE THREAD

**Issue by fabian-kramer** [flytreeleft/nexus3-keycloak-plugin#73]
Hello,

I'm experiencing the issue that after logging in to Keycloak and getting redirected to the nexus page, I see the normal view but I'm not signed in.
![image](https://user-images.githubusercontent.com/83784386/125399942-8a10b780-e3b1-11eb-993c-5d9b0c4f69be.png)
As you can see in the screenshot, I'm getting redirected from my keycloak login to nexus and then to the startpage.

I've installed the most recent version of openresty and followed your installation and setup steps (both "Usage" and "SSO"), and also tweaked everything as needed for my situation. There are too lua-resty-http, lua-resty-session and lua-resty-jwt installed via luarocks.
My vhost conf:
```
server {
  #listen 80;
  server_name nexus.[...];
  
  listen 443 ssl;
  ssl_certificate /etc/letsencrypt/certificates/[...]/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/certificates/[...]/privkey.pem;
  
  error_log /var/log/nginx/error.log; #debug;
  access_log /var/log/nginx/error.log; #main;

  set $oidc_logout_path "/logout";
  set $oidc_redirect_after_logout_uri "/";

  set $my_proto "http";
  if ($http_x_forwarded_proto = 'https') {
    set $my_proto "https";
  }
  if ($scheme = 'https') {
    set $my_proto "https";
  }
  if ( $http_user_agent = "ELB-HealthChecker/2.0" ) {
    set $my_proto "https";
  }
  # enforce https
  if ($my_proto != "https") {
    return 301 https://$host$request_uri;
  }

  client_max_body_size  1500m;

  location /   {
    add_header Access-Control-Allow-Origin https://login.[...];
    proxy_hide_header 'Access-Control-Allow-Origin';
    # Note: $http_host contains ip and port, but $host just contains ip only
    proxy_set_header    Host              $http_host;
    proxy_set_header    X-Forwarded-Proto $my_proto;
    #proxy_set_header    X-Real-IP         $remote_addr;
    #proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header    X-Keycloak-Sec-Auth $http_x_remote_user:$http_x_remote_user_access_token;
    #proxy_set_header    Authorization $http_authorization;
    proxy_set_header    X-Auth-Username $http_x_remote_user;
    proxy_set_header    X-Auth-Token $http_x_remote_user_access_token;
    # Note: make the HTTP header to be smaller
    proxy_hide_header X-Remote-User-Access-Token;

    set $oidc_disabled "false";
    # Disable OIDC when using maven client
    if ($http_user_agent ~* "^(Apache-Maven|docker)/.+$") {
      set $oidc_disabled "true";
    }
    # And disable OIDC when the header Authorization was specified
    if ($http_authorization !~* "^$") {
      set $oidc_disabled "false";
    }

    resolver 1.1.1.1;

    set $oidc_realm "[...]";
    # Note: change the client id and secret to the actual value
    set $oidc_client_id "nexus3";
    set $oidc_client_secret "[...]036f4eb79aeb";
    set $oidc_discovery "https://login.[...]:443/auth/realms/$oidc_realm/.well-known/openid-configuration";
    access_by_lua_file /etc/nginx/sites-available/oidc.lua;

    proxy_intercept_errors on;
    # Disable cache of assets
    proxy_cache off;
    proxy_read_timeout 600;
    proxy_connect_timeout 600;

    # Avoid to get address resolve error when starting
    proxy_pass      http://127.0.0.1:8888;

    sub_filter '</body>' '<script type="text/javascript">(function inject_logout() { var oidc_disabled = "$oidc_disabled"; if (oidc_disabled === "true") { return; } var dom = document.querySelectorAll("a[id^=\'nx-header-signout-\']")[0]; if (!dom) { setTimeout(inject_logout, 500); } else { dom.addEventListener("click", function (event) { event.stopPropagation(); window.location.href = "$oidc_logout_path"; }, true); }})();</script></body>';
    sub_filter_once on;

    # Just for debugging, you may not want it
    # header_filter_by_lua_block {
    #     for key, value in pairs(ngx.resp.get_headers()) do
    #         local val = type(value) == 'string' and {value} or value
    #         for k, v in ipairs(val) do
    #             for i=0, v:len(), 1024 do
    #                 ngx.log(ngx.DEBUG, 'Response Header: '..key..' -> '..v:sub(i + 1, i + 1024))
    #             end
    #         end
    #     end
    #     for key, value in pairs(ngx.req.get_headers()) do
    #         local val = type(value) == 'string' and {value} or value
    #         for k, v in ipairs(val) do
    #             for i=0, v:len(), 1024 do
    #                 ngx.log(ngx.DEBUG, 'Request Header: '..key..' -> '..v:sub(i + 1, i + 1024))
    #             end
    #         end
    #     end
    # }
  }

  # Override the logout action of Nexus
  location /service/rapture/session {
    if ($request_method ~* "^DELETE$") {
      # Redirect to the internal logout url
      return 302 $scheme://$http_host$oidc_logout_path;
    }
    # Login forbidden
    return 403;
  }
}
```
There is also an error in the nexus log that might help you to understand my problem. I hope you can help me
```
2021-07-13 06:18:00,031+0000 INFO  [qtp2102020182-261]  *UNKNOWN org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm - doGetAuthenticationInfo failed: Error executing http method [org.apache.http.client.methods.RequestBuilder@5fb8d4c9].
java.lang.RuntimeException: Error executing http method [org.apache.http.client.methods.RequestBuilder@5fb8d4c9].
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:79)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.execute(HttpMethodResponse.java:37)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakAdminClient.obtainUserInfo(KeycloakAdminClient.java:105)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.NexusKeycloakClient.authenticate(NexusKeycloakClient.java:70)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.NexusKeycloakClient.authenticate(NexusKeycloakClient.java:53)
	at org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm.doGetAuthenticationInfo(KeycloakAuthenticatingRealm.java:94)
	at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:571)
	at org.sonatype.nexus.security.authc.FirstSuccessfulModularRealmAuthenticator.doMultiRealmAuthentication(FirstSuccessfulModularRealmAuthenticator.java:59)
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:275)
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:275)
	at org.apache.shiro.nexus.NexusWebSecurityManager.login(NexusWebSecurityManager.java:84)
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:260)
	at org.apache.shiro.web.filter.authc.AuthenticatingFilter.executeLogin(AuthenticatingFilter.java:53)
	at org.apache.shiro.web.filter.authc.HttpAuthenticationFilter.onAccessDenied(HttpAuthenticationFilter.java:230)
	at org.apache.shiro.web.filter.AccessControlFilter.onAccessDenied(AccessControlFilter.java:133)
	at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162)
	at org.sonatype.nexus.security.authc.NexusBasicHttpAuthenticationFilter.onPreHandle(NexusBasicHttpAuthenticationFilter.java:86)
	at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:214)
	at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:189)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:85)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:101)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.sonatype.nexus.licensing.internal.LicensingRedirectFilter.doFilter(LicensingRedirectFilter.java:116)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:79)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.EnvironmentFilter.doFilter(EnvironmentFilter.java:101)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.sonatype.nexus.internal.web.HeaderPatternFilter.doFilter(HeaderPatternFilter.java:98)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.DynamicFilterPipeline.dispatch(DynamicFilterPipeline.java:104)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.sonatype.nexus.bootstrap.osgi.DelegatingFilter.doFilter(DelegatingFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to login.q01.esolution.services:443 [login.q01.esolution.services/10.241.18.44, login.q01.esolution.services/10.241.19.247] failed: Connection timed out (Connection timed out)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:52)
	... 79 common frames omitted
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 90 common frames omitted
```

**Comment by fabian-kramer** [comment]
I found my issue, it was the dns entry and everything is working now.
